import Link from 'next/link'

export default function TermsOfUse() {
  return (
    <div className="min-h-screen bg-[#0f172a] text-white flex flex-col">
      {/* Nav */}
      <nav className="flex items-center justify-between px-8 py-5 border-b border-white/10">
        <Link href="/" className="text-xl font-bold tracking-tight text-white">
          Clarix
        </Link>
      </nav>

      {/* Content */}
      <main className="flex-1 px-6 py-16">
        <div className="max-w-2xl mx-auto">
          <h1 className="text-3xl sm:text-4xl font-bold text-white mb-2">Terms of Use</h1>
          <p className="text-sm text-slate-500 mb-10">Last updated: August 2026</p>

          <div className="space-y-8 text-slate-300 leading-relaxed text-sm">
            <section>
              <h2 className="text-lg font-semibold text-white mb-2">1. Acceptance of these terms</h2>
              <p>
                Clarix is operated by Eleve Company OÜ (&quot;Clarix&quot;, &quot;we&quot;,
                &quot;our&quot;). By accessing this site or using the process analysis tool, you
                agree to these Terms of Use. If you don&apos;t agree, please don&apos;t use the
                service.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">2. Early-stage service</h2>
              <p>
                Clarix is currently in an early testing phase. Features, availability, and
                accuracy of results may change without notice, and the service may be interrupted
                or discontinued at any time. It is provided for evaluation purposes and should not
                be relied on as your sole source of business decision-making during this phase.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">3. Your content</h2>
              <p>
                Anything you type, upload, or otherwise submit when using the analysis tool
                (&quot;your content&quot;) remains yours. By submitting it, you grant Clarix a
                license to process it — including sending it to our AI provider (Anthropic) — for
                the sole purpose of generating your analysis and improving the service. You&apos;re
                responsible for making sure you have the right to share any content you submit,
                including information about your company, employees, or clients.
              </p>
              <p className="mt-2">
                Please don&apos;t submit content that is illegal, infringes someone else&apos;s
                rights, or includes personal data about third parties beyond what&apos;s
                reasonably necessary for the analysis.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">4. AI-generated output</h2>
              <p>
                Reports, recommendations, and action plans generated by Clarix are produced by an
                AI system and are provided for informational purposes only. They do not constitute
                professional consulting, legal, financial, or tax advice, and may contain
                inaccuracies. You&apos;re responsible for reviewing any output before relying on it
                or acting on it, and for any business decisions made using it.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">5. Acceptable use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-2 mt-2">
                <li>Use the service for any unlawful purpose</li>
                <li>Attempt to reverse-engineer, scrape, or disrupt the service</li>
                <li>Submit malicious code or attempt to gain unauthorized access to our systems</li>
                <li>Misrepresent your identity or affiliation when using the service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">6. Intellectual property</h2>
              <p>
                The Clarix name, branding, website, and underlying software are the property of
                Eleve Company OÜ and may not be copied, reproduced, or used without our written
                permission. This does not affect your ownership of your own content, as described
                in Section 3.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">7. No warranty</h2>
              <p>
                The service is provided &quot;as is&quot; and &quot;as available,&quot; without
                warranties of any kind, whether express or implied, including but not limited to
                accuracy, reliability, or fitness for a particular purpose.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">8. Limitation of liability</h2>
              <p>
                To the maximum extent permitted by law, Eleve Company OÜ shall not be liable for
                any indirect, incidental, or consequential damages arising from your use of, or
                inability to use, the service, including business decisions made based on
                AI-generated output.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">9. Termination</h2>
              <p>
                We may suspend or discontinue access to the service, in whole or in part, at any
                time, particularly given its current early-stage status.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">10. Governing law</h2>
              <p>
                These terms are governed by the laws of Estonia, without regard to conflict-of-law
                principles, unless mandatory consumer-protection laws of your country of residence
                provide otherwise.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">11. Changes to these terms</h2>
              <p>
                We may update these Terms of Use as the product evolves. We&apos;ll update the
                &quot;Last updated&quot; date above when we do.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-2">12. Contact</h2>
              <p>
                Questions about these terms? Reach out at{' '}
                <span className="text-white">eleve.eu@outlook.com</span>.
              </p>
            </section>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/10 py-6 px-8 flex items-center justify-between">
        <span className="text-sm font-bold text-white">Clarix</span>
        <div className="flex items-center gap-4 flex-wrap">
          <Link href="/privacy" className="text-xs text-slate-500 hover:text-slate-300 transition-colors">
            Privacy Policy
          </Link>
          <Link href="/impressum" className="text-xs text-slate-500 hover:text-slate-300 transition-colors">
            Impressum
          </Link>
          <a href="#" id="open_preferences_center" className="text-xs text-slate-500 hover:text-slate-300 transition-colors">
            Cookie Preferences
          </a>
          <p className="text-xs text-slate-600">© 2026 Eleve Company OÜ. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
